=== 514687572/STIP-generator/STIP-generator/src/main/resources/dtd/mybatis-generator-config_1_0.dtd
<!--
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<!ELEMENT generatorConfiguration (properties?, classPathEntry*, context+)>

<!ELEMENT properties EMPTY>
<!ATTLIST properties
  resource CDATA #IMPLIED
  url CDATA #IMPLIED>
  
<!ELEMENT classPathEntry EMPTY>
<!ATTLIST classPathEntry
  location CDATA #REQUIRED>

<!ELEMENT context (property*, plugin*, commentGenerator?, (connectionFactory | jdbcConnection), javaTypeResolver?,
                  javaModelGenerator, sqlMapGenerator?, javaClientGenerator?, table+)>
<!ATTLIST context
  id ID #REQUIRED
  defaultModelType CDATA #IMPLIED
  targetRuntime CDATA #IMPLIED
  introspectedColumnImpl CDATA #IMPLIED>

<!ELEMENT connectionFactory (property*)>
<!ATTLIST connectionFactory
  type CDATA #IMPLIED>

<!ELEMENT jdbcConnection (property*)>
<!ATTLIST jdbcConnection 
  driverClass CDATA #REQUIRED
  connectionURL CDATA #REQUIRED
  userId CDATA #IMPLIED
  password CDATA #IMPLIED>

<!ELEMENT javaTypeResolver (property*)>
<!ATTLIST javaTypeResolver
  type CDATA #IMPLIED>

<!ELEMENT javaModelGenerator (property*)>
<!ATTLIST javaModelGenerator
  targetPackage CDATA #REQUIRED
  targetProject CDATA #REQUIRED>

<!ELEMENT sqlMapGenerator (property*)>
<!ATTLIST sqlMapGenerator
  targetPackage CDATA #REQUIRED
  targetProject CDATA #REQUIRED>

<!ELEMENT javaClientGenerator (property*)>
<!ATTLIST javaClientGenerator
  type CDATA #REQUIRED
  targetPackage CDATA #REQUIRED
  targetProject CDATA #REQUIRED
  implementationPackage CDATA #IMPLIED>

<!ELEMENT table (property*, generatedKey?, columnRenamingRule?, (columnOverride | ignoreColumn | ignoreColumnsByRegex)*) >
<!ATTLIST table
  catalog CDATA #IMPLIED
  schema CDATA #IMPLIED
  tableName CDATA #REQUIRED
  alias CDATA #IMPLIED
  domainObjectName CDATA #IMPLIED
  mapperName CDATA #IMPLIED
  sqlProviderName CDATA #IMPLIED
  enableInsert CDATA #IMPLIED
  enableSelectByPrimaryKey CDATA #IMPLIED
  enableSelectByExample CDATA #IMPLIED
  enableUpdateByPrimaryKey CDATA #IMPLIED
  enableDeleteByPrimaryKey CDATA #IMPLIED
  enableDeleteByExample CDATA #IMPLIED
  enableCountByExample CDATA #IMPLIED
  enableUpdateByExample CDATA #IMPLIED
  selectByPrimaryKeyQueryId CDATA #IMPLIED
  selectByExampleQueryId CDATA #IMPLIED
  modelType CDATA #IMPLIED
  escapeWildcards CDATA #IMPLIED
  delimitIdentifiers CDATA #IMPLIED
  delimitAllColumns CDATA #IMPLIED>

<!ELEMENT columnOverride (property*)>
<!ATTLIST columnOverride
  column CDATA #REQUIRED
  property CDATA #IMPLIED
  javaType CDATA #IMPLIED
  jdbcType CDATA #IMPLIED
  typeHandler CDATA #IMPLIED
  isGeneratedAlways CDATA #IMPLIED
  delimitedColumnName CDATA #IMPLIED>

<!ELEMENT ignoreColumn EMPTY>
<!ATTLIST ignoreColumn
  column CDATA #REQUIRED
  delimitedColumnName CDATA #IMPLIED>

<!ELEMENT ignoreColumnsByRegex (except*)>
<!ATTLIST ignoreColumnsByRegex
  pattern CDATA #REQUIRED>

<!ELEMENT except EMPTY>
<!ATTLIST except
  column CDATA #REQUIRED
  delimitedColumnName CDATA #IMPLIED>

<!ELEMENT generatedKey EMPTY>
<!ATTLIST generatedKey
  column CDATA #REQUIRED
  sqlStatement CDATA #REQUIRED
  identity CDATA #IMPLIED
  type CDATA #IMPLIED>

<!ELEMENT columnRenamingRule EMPTY>
<!ATTLIST columnRenamingRule
  searchString CDATA #REQUIRED
  replaceString CDATA #IMPLIED>

<!ELEMENT plugin (property*)>
<!ATTLIST plugin
  type CDATA #REQUIRED>

<!ELEMENT property EMPTY>
<!ATTLIST property
  name CDATA #REQUIRED
  value CDATA #REQUIRED>

<!ELEMENT commentGenerator (property*)>
<!ATTLIST commentGenerator
  type CDATA #IMPLIED>

=== 514687572/STIP-generator/STIP-generator/src/main/java/com/stip/mybatis/generator/plugin/example/generatorConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration 
  PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN" 
  "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">

<generatorConfiguration>
    <properties resource="generator.properties" />  
    
    <context id="mysqlMap" targetRuntime="MyBatis3">

        <plugin type="org.mybatis.generator.plugins.SerializablePlugin" />
        <plugin type="org.mybatis.generator.plugins.ToStringPlugin" />
        <plugin type="com.stip.mybatis.generator.plugin.EqualsHashCodePlugin" />

		<plugin type="com.stip.mybatis.generator.plugin.ExampleClassPlugin">
           <property name="exampleTargetPackage" value="${exampleTargetPackage}"/>
           <property name="xmlTargetPackage" value="${xmlTargetPackage}"/>
           <property name="modelTargetPackage" value="${modelTargetPackage}"/>
           <property name="exampleTargetProject" value="${exampleTargetDir}"/>
  		</plugin>
  		
		<plugin type="com.stip.mybatis.generator.plugin.ExtendXmlMapperPlugin">
           <property name="exampleTargetPackage" value="${exampleTargetPackage}"/>
           <property name="xmlTargetPackage" value="${xmlTargetPackage}"/>
           <property name="modelTargetPackage" value="${modelTargetPackage}"/>
  		</plugin>
  		
		<plugin type="com.stip.mybatis.generator.plugin.ModelClassPlugin">
           <property name="modelTargetPackage" value="${modelTargetPackage}"/>
           <property name="modelTargetProject" value="${modelTargetDir}"/>
  		</plugin>
  		
        <plugin type="com.stip.mybatis.generator.plugin.MapperPlugin">
           <property name="daoTargetDir" value="${daoTargetDir}"/>
           <property name="daoTargetPackage" value="${daoTargetPackage}"/>
        </plugin>

        <plugin type="com.stip.mybatis.generator.plugin.MysqlPaginationPlugin">
        </plugin>

        <plugin type="com.stip.mybatis.generator.plugin.BooleanColumnPlugin"/>
        
        <commentGenerator>
            <property name="suppressAllComments" value="true" />
        </commentGenerator>
        
		<jdbcConnection driverClass="${jdbc.driverClassName}"
			connectionURL="${jdbc.url}"
			userId="${jdbc.username}" password="${jdbc.password}">
		</jdbcConnection>
 		
		<javaTypeResolver>
			<property name="forceBigDecimals" value="false" />
		</javaTypeResolver>
		<!--domain 代码 生成路径 -->
        <javaModelGenerator targetPackage="${modelTargetPackage}"
            targetProject="${modelTargetDir}">
            <property name="enableSubPackages" value="true" />
            <property name="trimStrings" value="true" />
        </javaModelGenerator> 
		
		<!--mapper 代码 生成路径 -->
        <sqlMapGenerator targetPackage="${xmlTargetPackage}"
            targetProject="${xmlTargetDir}">
            <property name="enableSubPackages" value="true" />
        </sqlMapGenerator>

        <table tableName="Users" alias="users" mapperName="UsersDao" domainObjectName="Users" ></table>
	</context>
</generatorConfiguration>

=== 514687572/STIP-generator/STIP-generator/src/main/resources/generatorConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
		"classpath:dtd/mybatis-generator-config_1_0.dtd">

<generatorConfiguration>
	<properties resource="generator.properties" />

	<context id="mysqlMap" targetRuntime="MyBatis3">

		<property name="xmlFormatter" value="com.stip.mybatis.generator.formatter.CustomXmlFormatter"/>

		<plugin type="org.mybatis.generator.plugins.SerializablePlugin" />
		<plugin type="org.mybatis.generator.plugins.ToStringPlugin" />
		<plugin type="com.stip.mybatis.generator.plugin.MysqlPaginationPlugin"/>
		<plugin type="com.stip.mybatis.generator.plugin.BooleanColumnPlugin" />

		<plugin type="com.stip.mybatis.generator.plugin.ExampleClassPlugin">
			<property name="targetProject" value="${targetProject}" />
			<property name="targetPackage" value="${targetPackage}" />
			<property name="exampleTargetPackage" value="${exampleTargetPackage}" />
			<property name="xmlTargetPackage" value="${xmlTargetPackage}" />
			<property name="modelTargetPackage" value="${modelTargetPackage}" />
			<property name="exampleTargetProject" value="${exampleTargetDir}" />
		</plugin>

		<plugin type="com.stip.mybatis.generator.plugin.ExtendXmlMapperPlugin">
			<property name="targetProject" value="${targetProject}" />
			<property name="targetPackage" value="${targetPackage}" />
			<property name="exampleTargetPackage" value="${exampleTargetPackage}" />
			<property name="xmlTargetPackage" value="${xmlTargetPackage}" />
			<property name="modelTargetPackage" value="${modelTargetPackage}" />
			<property name="enableXmlFormat" value="true"/>
			<property name="enableCache" value="true"/>
			<property name="enableComments" value="true"/>
		</plugin>

		<plugin type="com.stip.mybatis.generator.plugin.ModelClassPlugin">
			<property name="targetProject" value="${targetProject}" />
			<property name="targetPackage" value="${targetPackage}" />
			<property name="modelTargetPackage" value="${modelTargetPackage}" />
			<property name="modelTargetProject" value="${modelTargetDir}" />
		</plugin>

		<plugin type="com.stip.mybatis.generator.plugin.MapperPlugin">
			<property name="targetProject" value="${targetProject}" />
			<property name="targetPackage" value="${targetPackage}" />
			<property name="daoTargetDir" value="${daoTargetDir}" />
			<property name="daoTargetPackage" value="${daoTargetPackage}" />
			<property name="modelTargetPackage" value="${modelTargetPackage}" />
		</plugin>

		<plugin type="com.stip.mybatis.generator.plugin.ServiceInterfacePlugin">
			<property name="targetProject" value="${targetProject}" />
			<property name="targetPackage" value="${targetPackage}" />
			<property name="serviceTargetDir" value="${serviceTargetDir}" />
			<property name="serviceInterfaceTargetPackage" value="${serviceInterfaceTargetPackage}" />
			<property name="modelTargetPackage" value="${modelTargetPackage}" />
		</plugin>

		<plugin type="com.stip.mybatis.generator.plugin.ServicePlugin">
			<property name="targetProject" value="${targetProject}" />
			<property name="targetPackage" value="${targetPackage}" />
			<property name="serviceTargetDir" value="${serviceTargetDir}" />
			<property name="serviceTargetPackage" value="${serviceTargetPackage}" />
			<property name="modelTargetPackage" value="${modelTargetPackage}" />
			<property name="serviceInterfaceTargetPackage" value="${serviceInterfaceTargetPackage}" />
		</plugin>

		<plugin type="com.stip.mybatis.generator.plugin.LombokPlugin">
			<property name="useLombokPlugin" value="${useLombokPlugin}" />
			<property name="lombokAnnotations" value="${lombokAnnotations}" />
		</plugin>

		<commentGenerator>
			<property name="suppressAllComments" value="true" />
		</commentGenerator>

		<jdbcConnection driverClass="${jdbc.driverClassName}" connectionURL="${jdbc.url}" userId="${jdbc.username}" password="${jdbc.password}" />

		<javaTypeResolver>
			<property name="forceBigDecimals" value="false" />
		</javaTypeResolver>

		<!--domain 代码 生成路径 -->
		<javaModelGenerator targetPackage="${targetPackage}" targetProject="${targetProject}">
			<property name="trimStrings" value="true" />
		</javaModelGenerator>

		<!--mapper 代码 生成路径 -->
		<sqlMapGenerator targetPackage="${targetPackage}" targetProject="${targetProject}">
			<property name="enableSubPackages" value="true" />
		</sqlMapGenerator>
		<table catalog="${database}" tableName="${tableName}" ></table>


	</context>
</generatorConfiguration>
